### ISSUE TITLE
Unable to bootstrap application.

### ISSUE THREAD

**Issue by TristisOris** [waldur/waldur-docker-compose#12]
can't open pages
https://IP/
*/health-check
*/api
but /auth/admin works fine.

![image](https://github.com/user-attachments/assets/a72a4187-fc69-4ebc-a878-7abcadfce6b8)

`WRN ts=1729069485.7157836 msg=Caddyfile input is not formatted; run 'caddy fmt --overwrite' to fix inconsistencies adapter=caddyfile file=/etc/caddy/Caddyfile line=2`
`WRN ts=1729069485.7228742 logger=pki.ca.local msg=installing root certificate (you might be prompted for password) path=storage:pki/authorities/local/root.crt`

is it because i try to run it without domain name?

**Comment by livenson** [comment]
yes, I guess you use docker-compose? I think you need to access those APIs directly first -- and confirm with a browser that you accept broken certificates - then ajax calls would start working from browser app.

Or indeed get proper domain

**Comment by TristisOris** [comment]
we are using nginx reverse proxy, so i need waldur to listen http port.
but on 80 port i get `Error code: SSL_ERROR_RX_RECORD_TOO_LONG`
and with domain name `NS_ERROR_REDIRECT_LOOP`

looks i need to change caddy proxy config.

**Comment by livenson** [comment]
Afair caddy by default redirects all to https, so you might need to lookup into that - or perhaps forward from nginx to https ports but skip tls validation.

**Comment by TristisOris** [comment]
yep, i disable additional redirects, it works now. thanks.
