### ISSUE TITLE
Unable to create Organization

### ISSUE THREAD

**Issue by ictinc** [waldur/waldur-docker-compose#4]
Hi there,
I've setup everything according to the manual in this repo, everything seems to be working fine.
I'm trying to create an organization but it keeps declining to do so. No errors are given, nothing to indicate what is wrong but I suspect it has something to do with the Organization registration code.
What is a valid format for this?

Cheers, Ronald.

**Comment by livenson** [comment]
Hi, organization code by default can be any string, in some cases (if VAT check is enabled), it has to match with company registration in VIES. But what you describe here (and over email) seems rather like a bug introduced during migration to React (frontend is in the final stages of that). I will check a bit later and provide an update. Thanks for the report!

**Comment by ictinc** [comment]
Hi Livenson,
I setup a new local installation with docker-compose and was able to replicate the issue. However it seems like it's not related to the company registration after all.
I've left all optional fields blank in the billing details and only filled in the Organization registration code, Country and address. This time creating the organization went through as expected.
So there might be an issue related to either the postal code, Bank name, Bank Account or EU VAT ID.
I'm not sure if any of these fields require some type of format. I've used a Dutch format for postalcode (4 numbers and 2 letters) and IBAN format for the banking details.
Cheers.

**Comment by thomas-thaulow** [comment]
I had the same issue when using EU VAT ID. No error messages or validation, It simply would not proceed if leaving EU VAT ID active. By removing VAT ID, creation goes as expected.

**Comment by livenson** [comment]
The issue was indeed with that field - and you couldn't see it because errors were not propagated in that form. Fixed in https://github.com/opennode/waldur-homeport/commit/b8515efc939cb8397a821d4c92db1f3badfe55fd .
