### ISSUE TITLE
Can't login to Keycloak

### ISSUE THREAD

**Issue by kubeworkz** [waldur/waldur-docker-compose#8]
Keycloak doesn't seem to be letting me in with the keycloak admin pw I set in .env. I noticed in the keycloak container logs there's a message:
```
2022-12-08 22:27:25,589 ERROR [org.keycloak.services] (main) KC-SERVICES0010: Failed to add user 'admin' to realm 'master': user with username exists
```

Update: I was able to login to Keycloak Master realm with https://mydomain/auth/ and I noticed there's no user admin in the Waldur realm.

I manually created an admin user in the Waldur realm with the same password as the .env file and it still didn't allow me to login via Keycloak server.

**Comment by mattronix** [comment]
ah i see your using keycloak 22 i believe the /auth/ needs to be removed "/realms/master/.well-known/openid-configuration" instead of "/auth//realms/master/.well-known/openid-configuration"

**Comment by mattronix** [comment]
that fixed it

**Comment by livenson** [comment]
ok, old ticket, closing it

please reopen if you still face issues
